<?php

// Array of Elusive Icons
// Contributed by @WhatJustHappened
// Last updated: 14 Sept. 2013

defined('TEMPLAZA_FRAMEWORK') or exit();

add_filter( 'templaza-framework/font-icons', function(){
    return array (
        0 => 'fab fa-500px',
        1 => 'fab fa-accessible-icon',
        2 => 'fab fa-accusoft',
        3 => 'fab fa-acquisitions-incorporated',
        4 => 'fas fa-ad',
        5 => 'fas fa-address-book',
        6 => 'far fa-address-book',
        7 => 'fas fa-address-card',
        8 => 'far fa-address-card',
        9 => 'fas fa-adjust',
        10 => 'fab fa-adn',
        11 => 'fab fa-adobe',
        12 => 'fab fa-adversal',
        13 => 'fab fa-affiliatetheme',
        14 => 'fas fa-air-freshener',
        15 => 'fab fa-airbnb',
        16 => 'fab fa-algolia',
        17 => 'fas fa-align-center',
        18 => 'fas fa-align-justify',
        19 => 'fas fa-align-left',
        20 => 'fas fa-align-right',
        21 => 'fab fa-alipay',
        22 => 'fas fa-allergies',
        23 => 'fab fa-amazon',
        24 => 'fab fa-amazon-pay',
        25 => 'fas fa-ambulance',
        26 => 'fas fa-american-sign-language-interpreting',
        27 => 'fab fa-amilia',
        28 => 'fas fa-anchor',
        29 => 'fab fa-android',
        30 => 'fab fa-angellist',
        31 => 'fas fa-angle-double-down',
        32 => 'fas fa-angle-double-left',
        33 => 'fas fa-angle-double-right',
        34 => 'fas fa-angle-double-up',
        35 => 'fas fa-angle-down',
        36 => 'fas fa-angle-left',
        37 => 'fas fa-angle-right',
        38 => 'fas fa-angle-up',
        39 => 'fas fa-angry',
        40 => 'far fa-angry',
        41 => 'fab fa-angrycreative',
        42 => 'fab fa-angular',
        43 => 'fas fa-ankh',
        44 => 'fab fa-app-store',
        45 => 'fab fa-app-store-ios',
        46 => 'fab fa-apper',
        47 => 'fab fa-apple',
        48 => 'fas fa-apple-alt',
        49 => 'fab fa-apple-pay',
        50 => 'fas fa-archive',
        51 => 'fas fa-archway',
        52 => 'fas fa-arrow-alt-circle-down',
        53 => 'far fa-arrow-alt-circle-down',
        54 => 'fas fa-arrow-alt-circle-left',
        55 => 'far fa-arrow-alt-circle-left',
        56 => 'fas fa-arrow-alt-circle-right',
        57 => 'far fa-arrow-alt-circle-right',
        58 => 'fas fa-arrow-alt-circle-up',
        59 => 'far fa-arrow-alt-circle-up',
        60 => 'fas fa-arrow-circle-down',
        61 => 'fas fa-arrow-circle-left',
        62 => 'fas fa-arrow-circle-right',
        63 => 'fas fa-arrow-circle-up',
        64 => 'fas fa-arrow-down',
        65 => 'fas fa-arrow-left',
        66 => 'fas fa-arrow-right',
        67 => 'fas fa-arrow-up',
        68 => 'fas fa-arrows-alt',
        69 => 'fas fa-arrows-alt-h',
        70 => 'fas fa-arrows-alt-v',
        71 => 'fab fa-artstation',
        72 => 'fas fa-assistive-listening-systems',
        73 => 'fas fa-asterisk',
        74 => 'fab fa-asymmetrik',
        75 => 'fas fa-at',
        76 => 'fas fa-atlas',
        77 => 'fab fa-atlassian',
        78 => 'fas fa-atom',
        79 => 'fab fa-audible',
        80 => 'fas fa-audio-description',
        81 => 'fab fa-autoprefixer',
        82 => 'fab fa-avianex',
        83 => 'fab fa-aviato',
        84 => 'fas fa-award',
        85 => 'fab fa-aws',
        86 => 'fas fa-baby',
        87 => 'fas fa-baby-carriage',
        88 => 'fas fa-backspace',
        89 => 'fas fa-backward',
        90 => 'fas fa-bacon',
        91 => 'fas fa-bahai',
        92 => 'fas fa-balance-scale',
        93 => 'fas fa-balance-scale-left',
        94 => 'fas fa-balance-scale-right',
        95 => 'fas fa-ban',
        96 => 'fas fa-band-aid',
        97 => 'fab fa-bandcamp',
        98 => 'fas fa-barcode',
        99 => 'fas fa-bars',
        100 => 'fas fa-baseball-ball',
        
    );
});
