<?php

defined('TEMPLAZA_FRAMEWORK') or exit();

use TemPlazaFramework\Post_TypeFunctions;

if(!class_exists('TemplazaFramework_MetaBox_Our_Team')){
    class TemplazaFramework_MetaBox_Our_Team extends TemplazaFramework_MetaBox{

        public function register(){
            // Get all post types without templaza_style
            $metaboxes[] = array(
                'id'            => 'our_team-options',
                'title'         => esc_html__( 'Our Team Options', 'templaza-framework' ),
                'post_types'    => array('our_team'),
                'position'      => 'normal', // normal, advanced, side
                'priority'      => 'default', // high, core, default, low - Priorities of placement
                'store_each'    => true, // Store value of each fields to each post meta
                'sections'      => array(
                    array(
                        'fields' => array(
                            array(
                                'id'          => 'birthday',
                                'type'        => 'text',
                                'title'       => esc_html__('Birthday', 'templaza-framework'),
                                'placeholder' => esc_html__('Click to enter a date', 'templaza-framework'),
                            ),
                            array(
                                'id'          => 'phone',
                                'type'        => 'text',
                                'title'       => esc_html__('Phone Number', 'templaza-framework'),
                            ),
                            array(
                                'id'          => 'email',
                                'type'        => 'text',
                                'title'       => esc_html__('Email', 'templaza-framework'),
                            ),

                            array(
                                'id'       => 'social',
                                'type'     => 'tz_repeater',
                                'title' => esc_html__('Social', 'templaza-framework'),
                                'fields' => array(
                                    array(
                                        'id'       => 'social_url',
                                        'type'     => 'text',
                                        'title'    => esc_html__( 'Social url', 'templaza-framework' ),
                                    ),
                                    array(
                                        'id'          => 'social_icon',
                                        'type'        => 'select',
                                        'title'       => esc_html__( 'Login icon', 'templaza-framework' ),
                                        'data'        => 'fontawesome',
                                        'default'     => 'fas fa-facebook',
                                    ),

                                ),
                            ),
                        ),
                    ),
                ),
            );

            return $metaboxes;
        }

        public function hooks()
        {
            parent::hooks(); // TODO: Change the autogenerated stub

            add_filter("redux/options/{$this->prefix}templaza-options/wordpress_data/translate/post_type_value",
                array($this, 'meta_box_basic_post_type_value'), 10, 2);


            $post_type  = $this -> post_type -> get_post_type();

            if(post_type_exists($post_type) && $this -> post_type ->  get_current_screen_post_type() == $post_type){
                // Add header column to post type list
                if(method_exists($this,'post_type_table_head')) {
                    add_filter('manage_'.$post_type.'_posts_columns', array($this, 'post_type_table_head'));
                }
//                // Duplicate post action
//                add_action("templaza-framework/post-type/{$post_type}/duplicate", array($this, 'post_duplicate'), 11, 2);
//                // Set home for post type
//                add_action( 'admin_action_'.$post_type.'_set_default', array($this, 'post_type_set_default') );
            }

        }

        /*
         * Add columns for header custom post type in list page
         * @param array $columns
         * */
        public function post_type_table_head($columns){
            $columns = array(
                "cb"                 => "<input type=\"checkbox\" />",
                "title"              => esc_html__("Title", 'templaza-framework'),
//                "home"             => esc_html__("Default",'templaza-framework'),
                "date"               => esc_html__("Date",'templaza-framework')
            );
            return $columns;
        }

        /*
         * Add columns for content custom post type in list page
         * @param string $column_name
         * @param string $post_id
         * */
        public function post_type_table_content($column_name, $post_id ){
            if ($column_name == 'home') {
                $home   = get_post_meta($post_id,'home', true);
                $action = $this -> post_type -> get_post_type().'_set_default';
                $nonce  = wp_create_nonce( $action );
                $href   = 'admin.php?action='.$action.'&post='.$post_id.'&_wpnonce='
                    .$nonce.'" class="button button-micro'.($home?' disabled':'');
                if($home){
                    $href   = 'javascript:void();';
                }
                echo '<a href="'.$href.'" class="button button-micro'.($home?' disabled':'').'"'.($home?' disabled':'').'>';
                if($home){
                    echo '<span class="dashicons dashicons-star-filled featured"></span>';
                }else{
                    echo '<span class="dashicons dashicons-star-empty"></span>';
                }
                echo '</a>';
            }
        }

        /*
         * Order by query for custom post type in list page
         * @param array $vars
         * */
        public function post_type_orderby( $vars ) {
            if ( isset( $vars['orderby'] ) && 'home' == $vars['orderby'] ) {
                $vars = array_merge( $vars, array(
                    'meta_key' => 'home',
                    'orderby' => 'meta_value'
                ) );
            }

            return $vars;
        }

        /*
         * Reset value of select field with data is post
         * */
        public function meta_box_basic_post_type_value($value, $post_type){
            if(is_array($value)){
                return array();
            }else{
                return '';
            }
        }

    }
}