<?php

defined('TEMPLAZA_FRAMEWORK') or exit();

use TemPlazaFramework\Functions;
use TemPlazaFramework\Templates;
//die('43243');
//
//$options = Functions::get_theme_options();
//$header  = isset($options['enable-header'])?(bool) $options['enable-header']:true;
//$mode    = isset($options['header-mode'])?$options['header-mode']:'horizontal';
//
//if (!$header) {
//    return;
//}
//
//?>
<!--<section class="templaza-section templaza-header-section">-->
<?php
//Templates::load_my_header('header.' . $mode);
//
//$enable_sticky_menu = isset($options['enable-sticky'])?(bool) $options['enable-sticky']:false;
//if ($enable_sticky_menu) {
//    Templates::load_my_header('header.sticky');
//}
//?>
<!--</section>-->

<section class="templaza-section templaza-footer-section">
<div id="templaza-row-1528971561366" class="row no-gutters templaza-row"><div id="templaza-column-1530100662663" class="templaza-column col-lg-12"><div class="templaza-message" id="alert-message-711555907090073"><div id="system-message-container">
            </div>
        </div><div class="templaza-component" id="component-area-1121555907157112"><div class="templaza-component-area">

                <div id="sp-page-builder" class="sp-page-builder  page-4">


                    <div class="page-content">
                        <section id="section-id-1569834103461" class="sppb-section"><div class="sppb-row-container"><div class="sppb-row"><div class="sppb-col-md-12" id="column-wrap-id-1569834103462"><div id="column-id-1569834103462" class="sppb-column card"><div class="sppb-column-overlay"></div><div class="sppb-column-addons"><div id="section-id-1569834103463" class="sppb-section sppb-section-content-center"><div class="sppb-container-inner"><div class="sppb-row sppb-align-center"><div class="sppb-col-md-5" id="column-wrap-id-1569834103464"><div id="column-id-1569834103464" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1569834103465" class="sppb-addon-wrapper"><div id="sppb-addon-1569834103465" class="clearfix "><div class="sppb-addon sppb-addon-text-block  "><h2 class="sppb-addon-title">Auto Showroom</h2><div class="sppb-addon-content"><p>Auto Showroom Theme is clean and modern design which is useful for&nbsp;<strong>Car Dealer, Auto Dealer, Automotive WordPress website</strong>&nbsp;and any other automotive dealership business, who sell, buy or lease vehicles via website.</p>
                                                                                        <ul>
                                                                                            <li>11 Prebuilt-demo</li>
                                                                                            <li>Drag'n Drop Visual Page Builder</li>
                                                                                            <li>Fully Responsive Design</li>
                                                                                        </ul></div></div></div></div><div id="sppb-addon-wrapper-1569834103466" class="sppb-addon-wrapper"><div id="sppb-addon-1569834103466" class="clearfix "><div class="sppb-text-left"><a href="http://preview.themeforest.net/item/auto-showroom-car-dealership-wordpress-theme/full_screen_preview/15995336?_ga=2.155084799.61488690.1571630155-2072144412.1562553773" id="btn-1569834103466" class="sppb-btn  sppb-btn-custom sppb-btn-round">Learn About Auto Showroom</a></div></div></div></div></div></div><div class="sppb-col-md-7" id="column-wrap-id-1569834103467"><div id="column-id-1569834103467" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571389717083" class="sppb-addon-wrapper"><div id="sppb-addon-1571389717083" class="clearfix "><div class="sppb-addon sppb-addon-single-image sppb-text-center "><div class="sppb-addon-content"><div class="sppb-addon-single-image-container"><img class="sppb-img-responsive" src="/images/stories/autoshowroom/auto_showroom.png" alt="Image" title="" loading="lazy"></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></section><section id="section-id-1569830407299" class="sppb-section"><div class="sppb-row-container"><div class="sppb-row"><div class="sppb-col-md-12" id="column-wrap-id-1569830407298"><div id="column-id-1569830407298" class="sppb-column card"><div class="sppb-column-overlay"></div><div class="sppb-column-addons"><div id="section-id-1569830407300" class="sppb-section sppb-section-content-center"><div class="sppb-container-inner"><div class="sppb-row sppb-align-center"><div class="sppb-col-md-5" id="column-wrap-id-1569830407301"><div id="column-id-1569830407301" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1569830407311" class="sppb-addon-wrapper"><div id="sppb-addon-1569830407311" class="clearfix "><div class="sppb-addon sppb-addon-text-block  "><h2 class="sppb-addon-title">InteriArt</h2><div class="sppb-addon-content"><p><strong>Full solution for Interior, Architecture and Furniture site.</strong> No empty link, no broken link.&nbsp;Interiart Theme is clean and modern design which is useful for creating Furniture &amp; Interior Site site.</p>
                                                                                        <ul>
                                                                                            <li>Full solution for Furniture, Interior site</li>
                                                                                            <li>Page builder with Visual Composer</li>
                                                                                            <li>13 Prebuilt-demo in Interior, Architecture &amp; Furniture</li>
                                                                                        </ul></div></div></div></div><div id="sppb-addon-wrapper-1569831624023" class="sppb-addon-wrapper"><div id="sppb-addon-1569831624023" class="clearfix "><div class="sppb-text-left"><a href="https://1.envato.market/NEz9O" id="btn-1569831624023" class="sppb-btn  sppb-btn-custom sppb-btn-round">Learn About InteriArt</a></div></div></div></div></div></div><div class="sppb-col-md-7" id="column-wrap-id-1569830407304"><div id="column-id-1569830407304" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571389717088" class="sppb-addon-wrapper"><div id="sppb-addon-1571389717088" class="clearfix "><div class="sppb-addon sppb-addon-single-image sppb-text-center "><div class="sppb-addon-content"><div class="sppb-addon-single-image-container"><img class="sppb-img-responsive" src="/images/stories/interiart/interiart.png" alt="Image" title="" loading="lazy"></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></section><section id="section-id-1571624502386" class="sppb-section"><div class="sppb-row-container"><div class="sppb-row"><div class="sppb-col-md-12" id="column-wrap-id-1571624502387"><div id="column-id-1571624502387" class="sppb-column card"><div class="sppb-column-overlay"></div><div class="sppb-column-addons"><div id="section-id-1571624502388" class="sppb-section sppb-section-content-center"><div class="sppb-container-inner"><div class="sppb-row sppb-align-center"><div class="sppb-col-md-5" id="column-wrap-id-1571624502389"><div id="column-id-1571624502389" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502390" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502390" class="clearfix "><div class="sppb-addon sppb-addon-text-block  "><h2 class="sppb-addon-title">Aventura</h2><div class="sppb-addon-content"><p>Aventura provides <strong>full solution for Booking System</strong>. It is possible for <strong>customers to pay</strong> for tours directly in your website with Paypal and other payment services. Its stunning beauty, fashionable clean look and proper execution, accompanying with making use of Visual Composer, Aventura and Revolution Slider plugin, will help you to own an awesome travel site for your business.</p>
                                                                                        <ul>
                                                                                            <li>Full solution for Tour and Travel Agency site</li>
                                                                                            <li>Page builder with Visual Composer</li>
                                                                                            <li>7 Home Versions, 6 Header styles</li>
                                                                                        </ul></div></div></div></div><div id="sppb-addon-wrapper-1571624502391" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502391" class="clearfix "><div class="sppb-text-left"><a href="http://preview.themeforest.net/item/aventura-travel-tour-booking-system-wordpress-theme/full_screen_preview/20450670?_ga=2.252331211.358797208.1571626941-2072144412.1562553773" id="btn-1571624502391" class="sppb-btn  sppb-btn-custom sppb-btn-round">Learn About Aventura</a></div></div></div></div></div></div><div class="sppb-col-md-7" id="column-wrap-id-1571624502392"><div id="column-id-1571624502392" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502393" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502393" class="clearfix "><div class="sppb-addon sppb-addon-single-image sppb-text-center "><div class="sppb-addon-content"><div class="sppb-addon-single-image-container"><img class="sppb-img-responsive" src="/images/stories/aventura/aventura.png" alt="Image" title="" loading="lazy"></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></section><section id="section-id-1571624502402" class="sppb-section"><div class="sppb-row-container"><div class="sppb-row"><div class="sppb-col-md-12" id="column-wrap-id-1571624502403"><div id="column-id-1571624502403" class="sppb-column card"><div class="sppb-column-overlay"></div><div class="sppb-column-addons"><div id="section-id-1571624502404" class="sppb-section sppb-section-content-center"><div class="sppb-container-inner"><div class="sppb-row sppb-align-center"><div class="sppb-col-md-5" id="column-wrap-id-1571624502405"><div id="column-id-1571624502405" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502406" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502406" class="clearfix "><div class="sppb-addon sppb-addon-text-block  "><h2 class="sppb-addon-title">Meetup</h2><div class="sppb-addon-content"><p>Meetup is a simple and easy-to-use theme which is created for <strong>business sites and conference purposes</strong>.</p>
                                                                                        <p>There are <strong>lots of featured sections for Speakers, Event Schedule</strong>, FAQ’s, Registration Form and a location map. With many cutting-edge features, Meetup surely makes your works be effective and impressive among the other ones</p>
                                                                                        <ul>
                                                                                            <li>Clean, modern, multi-purpose design can be used for any type of website</li>
                                                                                            <li>Page builder with Visual Composer</li>
                                                                                            <li>9 Homepage version &amp; monthy update</li>
                                                                                        </ul></div></div></div></div><div id="sppb-addon-wrapper-1571624502407" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502407" class="clearfix "><div class="sppb-text-left"><a href="http://preview.themeforest.net/item/meetup-conference-event-wordpress-theme/full_screen_preview/13633735?_ga=2.268781111.796582062.1571628037-2072144412.1562553773" id="btn-1571624502407" class="sppb-btn  sppb-btn-custom sppb-btn-round">Learn About Meetup</a></div></div></div></div></div></div><div class="sppb-col-md-7" id="column-wrap-id-1571624502408"><div id="column-id-1571624502408" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502409" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502409" class="clearfix "><div class="sppb-addon sppb-addon-single-image sppb-text-center "><div class="sppb-addon-content"><div class="sppb-addon-single-image-container"><img class="sppb-img-responsive" src="/images/stories/meetup/meetup.png" alt="Image" title="" loading="lazy"></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></section><section id="section-id-1571624502418" class="sppb-section"><div class="sppb-row-container"><div class="sppb-row"><div class="sppb-col-md-12" id="column-wrap-id-1571624502419"><div id="column-id-1571624502419" class="sppb-column card"><div class="sppb-column-overlay"></div><div class="sppb-column-addons"><div id="section-id-1571624502420" class="sppb-section sppb-section-content-center"><div class="sppb-container-inner"><div class="sppb-row sppb-align-center"><div class="sppb-col-md-5" id="column-wrap-id-1571624502421"><div id="column-id-1571624502421" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502422" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502422" class="clearfix "><div class="sppb-addon sppb-addon-text-block  "><h2 class="sppb-addon-title">Space Home</h2><div class="sppb-addon-content"><p>With fully function of Real Estate site,<strong> powerful options &amp; tools, advanced search &amp; mapping</strong>, endlessly customizable with powerful admin options, 4 pre-built demos (more coming soon), 3 header layouts.</p>
                                                                                        <p>SPACE HOME is right fit for selling your <strong>Villa, Land, Apartment, House and Raw House</strong>. This Theme will provide you best details page that will describe your property well. It will be very helpful for selling your property and advertising your property.</p>
                                                                                        <ul>
                                                                                            <li>Full solution for Real Estate, Sell and Rental site</li>
                                                                                            <li>Fit function for Real Estate as (Listing Management, Google Map direction, Gallery, Agency, etc..)</li>
                                                                                            <li>Page builder with Visual Composer</li>
                                                                                        </ul></div></div></div></div><div id="sppb-addon-wrapper-1571624502423" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502423" class="clearfix "><div class="sppb-text-left"><a href="http://preview.themeforest.net/item/space-home-real-estate-wordpress-theme/full_screen_preview/17251245?_ga=2.131741903.1157419611.1571630454-2072144412.1562553773" id="btn-1571624502423" class="sppb-btn  sppb-btn-custom sppb-btn-round">Learn About Space Home</a></div></div></div></div></div></div><div class="sppb-col-md-7" id="column-wrap-id-1571624502424"><div id="column-id-1571624502424" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502425" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502425" class="clearfix "><div class="sppb-addon sppb-addon-single-image sppb-text-center "><div class="sppb-addon-content"><div class="sppb-addon-single-image-container"><img class="sppb-img-responsive" src="/images/stories/spacehome/spacehome.png" alt="Image" title="" loading="lazy"></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></section><section id="section-id-1571624502434" class="sppb-section"><div class="sppb-row-container"><div class="sppb-row"><div class="sppb-col-md-12" id="column-wrap-id-1571624502435"><div id="column-id-1571624502435" class="sppb-column card"><div class="sppb-column-overlay"></div><div class="sppb-column-addons"><div id="section-id-1571624502436" class="sppb-section sppb-section-content-center"><div class="sppb-container-inner"><div class="sppb-row sppb-align-center"><div class="sppb-col-md-5" id="column-wrap-id-1571624502437"><div id="column-id-1571624502437" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502438" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502438" class="clearfix "><div class="sppb-addon sppb-addon-text-block  "><h2 class="sppb-addon-title">Night Club</h2><div class="sppb-addon-content"><p>Night Club WordPress Theme is designed to become an ideal solution for users who intend to build up a website like <strong>music recording studio, music bands and groups, music clubs, night clubs and live music events</strong>.</p>
                                                                                        <ul>
                                                                                            <li>Clean, modern, multi-purpose design can be used for any type of website</li>
                                                                                            <li>Page builder with Visual Composer</li>
                                                                                            <li>Fullscreen video and Fullscreen slider for any page</li>
                                                                                        </ul></div></div></div></div><div id="sppb-addon-wrapper-1571624502439" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502439" class="clearfix "><div class="sppb-text-left"><a href="http://preview.themeforest.net/item/1040-night-club-dj-party-music-club-wordpress-theme/full_screen_preview/18782397?_ga=2.76568854.207217631.1571630521-2072144412.1562553773" id="btn-1571624502439" class="sppb-btn  sppb-btn-custom sppb-btn-round">Learn About Night Club</a></div></div></div></div></div></div><div class="sppb-col-md-7" id="column-wrap-id-1571624502440"><div id="column-id-1571624502440" class="sppb-column"><div class="sppb-column-addons"><div id="sppb-addon-wrapper-1571624502441" class="sppb-addon-wrapper"><div id="sppb-addon-1571624502441" class="clearfix "><div class="sppb-addon sppb-addon-single-image sppb-text-center "><div class="sppb-addon-content"><div class="sppb-addon-single-image-container"><img class="sppb-img-responsive" src="/images/stories/nightclub/nightclub.png" alt="Image" title="" loading="lazy"></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></section>			</div>
                </div>

            </div></div></div></div>
</section>
</div>