<?php

defined( 'ABSPATH' ) || exit;

if(!defined('TEMPLAZA_FRAMEWORK_PATH')){
    define('TEMPLAZA_FRAMEWORK_PATH', dirname( dirname(__FILE__)));
}
if(!defined('TEMPLAZA_FRAMEWORK_PLUGIN_DIR_PATH')){
    define('TEMPLAZA_FRAMEWORK_PLUGIN_DIR_PATH', dirname(TEMPLAZA_FRAMEWORK_PATH ));
}
if(!defined('TEMPLAZA_FRAMEWORK')){
    define('TEMPLAZA_FRAMEWORK', basename(TEMPLAZA_FRAMEWORK_PATH));
}
if(!defined('TEMPLAZA_FRAMEWORK_NAME')){
    define('TEMPLAZA_FRAMEWORK_NAME', TEMPLAZA_FRAMEWORK);
}
if(!defined('TEMPLAZA_FRAMEWORK_CORE_PATH')){
    define('TEMPLAZA_FRAMEWORK_CORE_PATH', TEMPLAZA_FRAMEWORK_PATH.'/framework');
}
if(!defined('TEMPLAZA_FRAMEWORK_PREFIX')){
    define('TEMPLAZA_FRAMEWORK_PREFIX', 'tzfrm');
}
if(!defined('TEMPLAZA_FRAMEWORK_OPTION_PATH')){
    define('TEMPLAZA_FRAMEWORK_OPTION_PATH', TEMPLAZA_FRAMEWORK_CORE_PATH.'/options');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_PATH')){
    define('TEMPLAZA_FRAMEWORK_THEME_PATH', get_template_directory().'/templaza-framework');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_PATH_OPTION')){
    define('TEMPLAZA_FRAMEWORK_THEME_PATH_OPTION', TEMPLAZA_FRAMEWORK_THEME_PATH.'/options');
}