<?php

defined( 'ABSPATH' ) || exit;

if(!defined('TEMPLAZA_FRAMEWORK_PATH')){
    define('TEMPLAZA_FRAMEWORK_PATH', dirname( dirname(__FILE__)));
}
if(!defined('TEMPLAZA_FRAMEWORK_PLUGIN_DIR_PATH')){
    define('TEMPLAZA_FRAMEWORK_PLUGIN_DIR_PATH', dirname(TEMPLAZA_FRAMEWORK_PATH ));
}
if(!defined('TEMPLAZA_FRAMEWORK')){
    define('TEMPLAZA_FRAMEWORK', basename(TEMPLAZA_FRAMEWORK_PATH));
}
if(!defined('TEMPLAZA_FRAMEWORK_NAME')){
    define('TEMPLAZA_FRAMEWORK_NAME', TEMPLAZA_FRAMEWORK);
}
if(!defined('TEMPLAZA_FRAMEWORK_CORE_PATH')){
    define('TEMPLAZA_FRAMEWORK_CORE_PATH', TEMPLAZA_FRAMEWORK_PATH.'/framework');
}
if(!defined('TEMPLAZA_FRAMEWORK_LIBRARY_PATH')){
    define('TEMPLAZA_FRAMEWORK_LIBRARY_PATH', TEMPLAZA_FRAMEWORK_CORE_PATH.'/libraries');
}
if(!defined('TEMPLAZA_FRAMEWORK_PREFIX')){
    define('TEMPLAZA_FRAMEWORK_PREFIX', 'tzfrm');
}
if(!defined('TEMPLAZA_FRAMEWORK_OPTION_PATH')){
    define('TEMPLAZA_FRAMEWORK_OPTION_PATH', TEMPLAZA_FRAMEWORK_CORE_PATH.'/options');
}
if(!defined('TEMPLAZA_FRAMEWORK_FIELD_PATH')){
    define('TEMPLAZA_FRAMEWORK_FIELD_PATH', TEMPLAZA_FRAMEWORK_CORE_PATH.'/fields');
}
if(!defined('TEMPLAZA_FRAMEWORK_INCLUDES_PATH')){
    define('TEMPLAZA_FRAMEWORK_INCLUDES_PATH', TEMPLAZA_FRAMEWORK_PATH.'/includes');
}
if(!defined('TEMPLAZA_FRAMEWORK_SHORTCODES_PATH')){
    define('TEMPLAZA_FRAMEWORK_SHORTCODES_PATH', TEMPLAZA_FRAMEWORK_PATH.'/shortcodes');
}
if(!defined('TEMPLAZA_FRAMEWORK_METABOXES_PATH')){
    define('TEMPLAZA_FRAMEWORK_METABOXES_PATH', TEMPLAZA_FRAMEWORK_PATH.'/metaboxes');
}
if(!defined('TEMPLAZA_FRAMEWORK_SCSS_PATH')){
    define('TEMPLAZA_FRAMEWORK_SCSS_PATH', TEMPLAZA_FRAMEWORK_CORE_PATH.'/assets/scss');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_PATH')){
    define('TEMPLAZA_FRAMEWORK_THEME_PATH', get_template_directory().'/templaza-framework');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_CSS_PATH')){
    define('TEMPLAZA_FRAMEWORK_THEME_CSS_PATH', TEMPLAZA_FRAMEWORK_THEME_PATH.'/css');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_SCSS_PATH')){
    define('TEMPLAZA_FRAMEWORK_THEME_SCSS_PATH', TEMPLAZA_FRAMEWORK_THEME_PATH.'/scss');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_PATH_OPTION')){
    define('TEMPLAZA_FRAMEWORK_THEME_PATH_OPTION', TEMPLAZA_FRAMEWORK_THEME_PATH.'/options');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_PATH_TEMPLATE')){
    define('TEMPLAZA_FRAMEWORK_THEME_PATH_TEMPLATE', TEMPLAZA_FRAMEWORK_THEME_PATH.'/templates');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_PATH_SHORTCODES')){
    define('TEMPLAZA_FRAMEWORK_THEME_PATH_SHORTCODES', TEMPLAZA_FRAMEWORK_THEME_PATH.'/shortcodes');
}
if(!defined('TEMPLAZA_FRAMEWORK_THEME_PATH_METABOXES')){
    define('TEMPLAZA_FRAMEWORK_THEME_PATH_METABOXES', TEMPLAZA_FRAMEWORK_THEME_PATH.'/metaboxes');
}